######## PRUEBA PETICIONES #######
##### Extension REST Client #####

### Obtener todos los deportistas
GET http://localhost:3000/api/deportistas
Content-Type: application/json

###

### Crear un nuevo deportista
POST http://localhost:3000/api/deportistas
Content-Type: application/json

{
  "nombre": "Mateo",
  "apellido": "García",
  "edad": 10,
  "categoria": "Básico"
}

###

### Actualizar un deportista 
PUT http://localhost:3000/api/deportistas/6879a4cc23cfe71adceca5cd
Content-Type: application/json

{
  "nombre": "Lucía",
  "apellido": "Martínez",
  "edad": 15,
  "categoria": "Juvenil"
}

###

### Eliminar un deportista
DELETE http://localhost:3000/api/deportistas/
Content-Type: application/json
